cse416proj/mapsterpiece_project

client/src/App.test.js
- Added test case to ensure all the expected element are present upon running
=> Add test case for UI

client/src/components/modals/DeletePostModal.js, client/src/components/screens/auth/Login.js, client/src/components/screens/community/CommunityScreen.js, client/src/components/screens/create/post/CreatePost.js, client/src/contexts/auth/auth-request-api/index.js, client/src/contexts/auth/index.js, client/src/contexts/post/index.js, client/src/contexts/post/post-request-api/index.js, server/app.js, server/auth/index.js, server/controllers/auth-controller.js, server/controllers/post-controller.js, server/models/comment-model.js, server/models/post-model.js, server/models/subcomment-model.js, server/models/user-model.js, server/routes/post-router.js
1. Added comment model, post model, and subcomment model
2. Created backend api `api-post/createPost`
3. Modified frontend create post screen; when a post has been successfully created it will show an alert "post created, redirecting..." and then redirect user back to their home page
4. Post that has been successfully created will show up in database but not on our UI as of now, as it will be work on in another PR
=> Added create post functionality

client/src/App.js, client/src/components/appbars/MaybeShowNavBar.js, client/src/components/cards/ActionButtons.js, client/src/components/cards/DynamicCard.js, client/src/components/cards/MapCard.js, client/src/components/cards/PostCard.js, client/src/components/modals/DeletePostModal.js, client/src/components/screens/community/CommunityScreen.js, client/src/components/screens/home/UserHomeScreen.js, client/src/components/screens/post/PostComment.js, client/src/components/screens/post/PostDetailScreen.js, client/src/components/screens/profile/Profile.js, client/src/contexts/auth/index.js, client/src/contexts/post/index.js, client/src/contexts/post/post-request-api/index.js, client/src/contexts/store/index.js, client/src/contexts/store/store-request-api/index.js, server/app.js, server/controllers/auth-controller.js, server/controllers/post-controller.js, server/controllers/store-controller.js, server/routes/post-router.js, server/routes/store-router.js
1. UI gets updated accordingly after successful creating a post
2. get all posts for a user (for home screen and profile screen)
3. get all posts in general (for community screen)
4. able to delete post by id (from community screen, user home screen, and profile screen)
5. get post by id, viewing specific post
6. add comment to a specific post
7. foolproof design (only logged in user can add comments, can only delete your own posts, etc)
8. database gets updated accordingly for each successful operation
=> shiying's build 3

client/src/components/screens/home/UserHomeScreen.js, server/routes/post-router.js, server/routes/store-router.js
Found out that when visiting community screen it will throw 'unauthorize' error for guests. Fixed the issue
=> Removed authorization requirement for get posts requests 

client/src/components/screens/post/PostComment.js, client/src/components/screens/profile/Profile.js, client/src/contexts/post/index.js, client/src/contexts/post/post-request-api/index.js, server/controllers/post-controller.js, server/routes/post-router.js
1. User able to add subcomments to a post comment
2. Foolproof design
3. fixed the ui a bit
=> Add subcomment functionality

client/src/App.js, client/src/components/appbars/MapEditTopBar.js, client/src/components/appbars/NavBar.js, client/src/components/cards/DynamicCard.js, client/src/components/index.js, client/src/components/modals/DeleteAccountModal.js, client/src/components/screens/community/CommunityScreen.js, client/src/components/screens/profile/Profile.js, client/src/components/screens/profile/ProfileCard.js, client/src/contexts/auth/auth-request-api/index.js, client/src/contexts/post/index.js, client/src/contexts/store/index.js, client/src/contexts/store/store-request-api/index.js, client/src/contexts/user/index.js, client/src/contexts/user/user-request-api/index.js, server/app.js, server/controllers/auth-controller.js, server/controllers/post-controller.js, server/controllers/store-controller.js, server/controllers/user-controller.js, server/routes/auth-router.js, server/routes/store-router.js, server/routes/user-router.js
1. Get user by id --- when navigating to user profile the url will be display as 'profile/:id'
2. Get all users
3. delete user by id; when user click on delete it will ask for confirmation and then proceed with the deletion
4. Fixed original delete post bug since the post has to be deleted from the user as well
=> Additional build 3

client/src/components/cards/ActionButtons.js, client/src/components/cards/DynamicCard.js, client/src/components/cards/MapCard.js, client/src/components/index.js, client/src/components/modals/DeleteMapModal.js, client/src/components/modals/DeletePostModal.js, client/src/components/screens/community/CommunityScreen.js, client/src/components/screens/home/UserHomeScreen.js, client/src/components/screens/listFilter/MapsCardSection.js, client/src/components/screens/listFilter/MapsPostsCardSelection.js, client/src/components/screens/listFilter/PostsCardSelection.js, client/src/components/screens/listFilter/UsersCardSelection.js, client/src/components/screens/post/PostComment.js, client/src/components/screens/post/PostDetailScreen.js, client/src/components/screens/profile/Profile.js, client/src/components/screens/search/SearchScreen.js, client/src/contexts/map/index.js, client/src/contexts/map/map-request-api/index.js, client/src/contexts/store/index.js, server/controllers/map-controller.js, server/controllers/post-controller.js
1. user can now delete map&post
2. update foolproof design
Note: may need test as its newly merged code
=> delete map&post + update foolproof design

.idea/workspace.xml, client/src/App.js, client/src/components/appbars/CommentsSideBox.js, client/src/components/appbars/MapDetailOwnerTopBar.js, client/src/components/appbars/MapDetailUserTopBar.js, client/src/components/cards/DynamicCard.js, client/src/components/cards/PostCard.js, client/src/components/modals/DeleteMapModal.js, client/src/components/screens/map/MapDetailsScreen.js, client/src/styles/Map.css, server/package-lock.json, server/package.json
=> Merge Sahil's code for published map view

client/src/App.js, client/src/components/appbars/MapDetailOwnerTopBar.js, client/src/components/appbars/MapEditSideBar.js, client/src/components/appbars/MapEditTopBar.js, client/src/components/cards/DynamicCard.js, client/src/components/screens/edit/map/MapEditScreen.js, client/src/components/screens/map/MapDetailsScreen.js, client/src/components/screens/map/display/MapScreen.js, client/src/contexts/map/index.js, server/auth.test.js
1. Route link edited to view edit/published map by id
2. Updated view for edit/published map, and now shows title & tags
3. able to delete unpublished maps and both edit/published map have popup delete modal
=> Updated routing and view for map editing & publishing

client/src/components/screens/profile/Profile.js, server/controllers/store-controller.js, server/controllers/user-controller.js
1. user able to see other people's posts when clicking on their profile
=> fixed seeing other user's post on their profile

client/src/components/appbars/MapDetailOwnerTopBar.js, client/src/components/appbars/MapEditTopBar.js, client/src/components/cards/ActionButtons.js, client/src/components/cards/DynamicCard.js, client/src/components/cards/MapCard.js, client/src/contexts/map/index.js, client/src/contexts/map/map-request-api/index.js, server/controllers/map-controller.js, server/routes/map-router.js
1. can publish/unpublished from map card dropdown menu
2. can publish on map edit screen
3. can unpublish on map detail screen
=> Added publish/unpublished feature

client/src/components/appbars/MapDetailTopBar.js, client/src/components/appbars/MapEditTopBar.js, client/src/contexts/map/index.js
as title:
1. unpublish from map-detail will redirect to map-edit
2. publish from map-edit will redirect to map-detail
=> Added page redirection for publish & unpublish map

client/src/components/screens/map/display/MapScreen.js
1. Upload kml will now render name in county level
=> change name rendering

client/cypress/e2e/spec_local.cy.js, client/src/components/screens/home/Hero.js, client/src/components/screens/home/HomeNavCard.js
changed 1st 5 cypress test cases
=> attempt to fix cypress

client/src/components/appbars/mapDetail/MapDetailTopBar.js, client/src/components/screens/map/detail/MapScreen.js, client/src/contexts/map/index.js, client/src/contexts/map/map-request-api/index.js, server/controllers/map-controller.js, server/routes/map-router.js
1. Logged in user is able to liked/disliked a published map in map detail screen
2. User cannot liked/disliked map twice
3. Guest cannot liked/disliked map
4. Revert backend geojson parsing to choiying's way, also changed frontend name parsing a bit
=> map like/dislike functionality

client/package-lock.json, client/package.json, client/src/components/appbars/mapDetail/MapCommentSideBar.js, client/src/components/appbars/query/SearchBar.js, client/src/components/appbars/query/SideNavBar.js, client/src/components/cards/card/MapCard.js, client/src/components/cards/card/PostCard.js, client/src/components/cards/cardListFilter/MapsPostsCardSelection.js, client/src/components/screens/community/CommunityScreen.js, client/src/components/screens/search/SearchScreen.js, client/src/contexts/map/index.js, client/src/contexts/store/index.js, server/controllers/map-controller.js, server/routes/map-router.js
1. show cards in search screen
2. sort All maps&posts by alphabetical order, recent time
3. adjust typography when user/owner come to search screen
4. adjust sort by edit time to only show for owner search screen
5. backend duplicateMap function
=> sort cards in search screen

server/test.js
=> added backend test

client/src/contexts/store/index.js
1. able to filter maps by mapTypes
2. able to filter posts by tags/title/content
=> fix filtering by map types for community & search screen

client/src/components/appbars/mapDetail/MapDetailTopBar.js, client/src/components/appbars/mapEdit/MapEditSideBar.js, client/src/components/appbars/mapEdit/MapEditTopBar.js, client/src/components/screens/create/map/CreateMap.js, client/src/components/screens/map/detail/MapDetailsScreen.js, client/src/components/screens/map/detail/MapScreen.js, client/src/components/screens/map/edit/MapEditScreen.js, client/src/contexts/map/index.js, client/src/contexts/map/map-request-api/index.js, server/controllers/map-controller.js
1. publish will save data
2. save edit will save map type and map data change
=> fix publish save

client/src/components/screens/map/control/LegendControl.js, client/src/components/screens/map/detail/MapScreen.js
=> changed legend

client/src/components/appbars/mapEdit/MapEditSideBar.js, client/src/components/cards/card/ActionButtons.js, client/src/components/screens/create/map/SelectMapType.js, client/src/components/screens/map/detail/MapScreen.js
1. Bring back 'regular' for region coloring
=> bring back regular map type

client/src/components/appbars/NavBar.js, client/src/components/cards/card/DynamicCard.js, client/src/components/modals/DataEntryModal.js, client/src/components/modals/DeleteAccountModal.js, client/src/components/screens/auth/Login.js, client/src/components/screens/auth/Register.js, client/src/components/screens/auth/password/ForgotPassword.js, client/src/components/screens/auth/password/ResetPassword.js, client/src/components/screens/commonProps/loading/Loading.js, client/src/components/screens/commonProps/searchAndSort/SortBy.js, client/src/components/screens/community/CommunityScreen.js, client/src/components/screens/home/user/UserHomeScreen.js, client/src/components/screens/map/detail/MapScreen.js, client/src/components/screens/map/edit/MapEditScreen.js, client/src/components/screens/post/edit/PostEditScreen.js, client/src/components/screens/profile/Profile.js, client/src/components/screens/profile/ProfileCard.js, client/src/components/warnings/Warning.js, client/src/contexts/auth/index.js, client/src/contexts/map/index.js, client/src/contexts/post/index.js, client/src/contexts/store/index.js, client/src/contexts/user/index.js, client/src/styles/Auth.css, client/src/styles/Profile.css, client/src/styles/Query.css, server/controllers/auth-controller.js
1. Loading effect now on home, profile and community
2. Clear error display across auth screens (login, register, etc.) as previously error doesn't get cleared when jumping btwn pages
3. Added sort by to home, profile, etc.
4. Handle request error by adding try & catch
=> Render load effect on home, profile and community, also tried to handle request error
